/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IDutchSwapFactoryInterface extends ethers.utils.Interface {
  functions: {
    "deployDutchAuction(address,uint256,uint256,uint256,address,uint256,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deployDutchAuction",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployDutchAuction",
    data: BytesLike
  ): Result;

  events: {};
}

export class IDutchSwapFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IDutchSwapFactoryInterface;

  functions: {
    deployDutchAuction(
      _token: string,
      _tokenSupply: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _paymentCurrency: string,
      _startPrice: BigNumberish,
      _minimumPrice: BigNumberish,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deployDutchAuction(address,uint256,uint256,uint256,address,uint256,uint256,address)"(
      _token: string,
      _tokenSupply: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _paymentCurrency: string,
      _startPrice: BigNumberish,
      _minimumPrice: BigNumberish,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  deployDutchAuction(
    _token: string,
    _tokenSupply: BigNumberish,
    _startDate: BigNumberish,
    _endDate: BigNumberish,
    _paymentCurrency: string,
    _startPrice: BigNumberish,
    _minimumPrice: BigNumberish,
    _wallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deployDutchAuction(address,uint256,uint256,uint256,address,uint256,uint256,address)"(
    _token: string,
    _tokenSupply: BigNumberish,
    _startDate: BigNumberish,
    _endDate: BigNumberish,
    _paymentCurrency: string,
    _startPrice: BigNumberish,
    _minimumPrice: BigNumberish,
    _wallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployDutchAuction(
      _token: string,
      _tokenSupply: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _paymentCurrency: string,
      _startPrice: BigNumberish,
      _minimumPrice: BigNumberish,
      _wallet: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "deployDutchAuction(address,uint256,uint256,uint256,address,uint256,uint256,address)"(
      _token: string,
      _tokenSupply: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _paymentCurrency: string,
      _startPrice: BigNumberish,
      _minimumPrice: BigNumberish,
      _wallet: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deployDutchAuction(
      _token: string,
      _tokenSupply: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _paymentCurrency: string,
      _startPrice: BigNumberish,
      _minimumPrice: BigNumberish,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deployDutchAuction(address,uint256,uint256,uint256,address,uint256,uint256,address)"(
      _token: string,
      _tokenSupply: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _paymentCurrency: string,
      _startPrice: BigNumberish,
      _minimumPrice: BigNumberish,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployDutchAuction(
      _token: string,
      _tokenSupply: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _paymentCurrency: string,
      _startPrice: BigNumberish,
      _minimumPrice: BigNumberish,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deployDutchAuction(address,uint256,uint256,uint256,address,uint256,uint256,address)"(
      _token: string,
      _tokenSupply: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _paymentCurrency: string,
      _startPrice: BigNumberish,
      _minimumPrice: BigNumberish,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
